services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_vue_app
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: laravel_vue_app_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" 
    depends_on:
      - app
    networks:
      - app_network

  database:
    image: mysql:8
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app_network
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_admin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - app_network

volumes:
  database_data:
    driver: local

networks:
  app_network:
    driver: bridge